config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  root 'welcome#index'
  get 'tracker' => 'trackers#index'
  get 'overview' => 'attendance#overview'
  get 'attendance' => 'attendance#index'
  get 'users' => 'users#index'
  post 'trackers/timein' => 'trackers#timein'
  post 'trackers/timeout' => 'trackers#timeout'
  post 'trackers/new' => 'trackers#new'
  get 'trackers/userlog' => 'users#userlog'
  get 'trackers/timeout' => 'trackers#timeout'
  get 'trackers/show' => 'trackers#show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
end

app/models/db/migrate/20180808085838_create_employees.rb
class CreateEmployees < ActiveRecord::Migration[5.2]
  def change
    create_table :employees do |t|
      t.integer :employeenumber
      t.text :firstname
      t.text :lastname
      t.string :email
      t.text :position
      t.text :client
      t.text :startdate
      t.timestamps
    end
  end
end

app/models/db/schema.rb
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 2018_08_08_085838) do

  create_table "employees", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8", force: :cascade do |t|
    t.integer "employeenumber"
    t.text "firstname"
    t.text "lastname"
    t.string "email"
    t.text "position"
    t.text "client"
    t.text "startdate"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "users", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8", force: :cascade do |t|
    t.string "email", default: "", null: false
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer "sign_in_count", default: 0, null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string "current_sign_in_ip"
    t.string "last_sign_in_ip"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
  end

end

app/models/employee.rb
class Employee < ApplicationRecord

  validates  :firstname, presence: true, length: {minimum: 3, maximum: 50}
  validates  :lastname, presence: true, length: {minimum: 2, maximum: 50}
  # validates  :email, presence: true, length: {minimum: 7, maximum: 50}
  # validates  :position, presence: true, length: {minimum: 5, maximum: 100}
  # validates  :client, presence: true, length: {minimum: 3, maximum: 100}

end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :user
end

app/models/track_time.rb
class TrackTime < ApplicationRecord
  belongs_to :user
end

app/models/tracker.rb
class Tracker < ApplicationRecord
  # before_action :authenticate_user!
  belongs_to :user


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # has_many :attendances
  # has_many :track_times
  has_many :trackers
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :firstname, presence: true, length: {minimum: 3, maximum: 50}
  validates :lastname, presence: true, length: {minimum: 3, maximum: 50}
  def admin?
    has_attribute?(:admin) == true
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  skip_before_action :verify_authenticity_token
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname])
  end
  def after_sign_in_path_for(resource)
    user_path(current_user) #your path
  end
end

app/controllers/attendance_controller.rb
class AttendanceController < ApplicationController
  def overview
    @trackers = Tracker.all
    @users = User.all
  end
end

app/controllers/trackers_controller.rb
class TrackersController < ApplicationController
  def index
  @trackers = Tracker.all
  @users = User.all
  end
  def new
    @trackers = Tracker.new
  end

  def timein
      @user= User.find(current_user.id)


      @tracker = Tracker.new(user_id: @user.id, loggin_in: Time.now - 16.hours )
      @tardy = @tracker.loggin_in - 7.hours
      if (@tracker.loggin_in <= @tardy )
          @tracker.tardy = @tracker.loggin - @tardy
      else
        @tracker.tardy = 0
      end
      @tracker.save

     redirect_to trackers_userlog_path
      end
  def timeout
    @last_log = current_user.trackers.last
    if @last_log.loggin_in != nil || @last_log.loggin_out == nil
      @last_log.update(loggin_out: Time.now - 16.hours)
      @last_log.hours = @last_log.loggin_out - @last_log.loggin_in
      @last_log.save

    end
    redirect_to trackers_userlog_path
  end

  def create
    @tracker = Tracker.new(tracker_params)
    @tracker.save
    redirect_to trackers_show
  end

  def update

  end

  def show
    @trackers = current_user.trackers

  end

  private
  def tracker_params
    params.require(:tracker).permit(:loggin_in, :loggin_out)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @last_log = current_user.trackers.last
  end
  def index
    # @attend= Tracker.new(user_id: current_user.id, loggin_in: @login, loggin_out: @logout)
    # if @login != nil && @logout != nil
    #   @attend.save
    # end
    @users = User.all
    @trackers = Tracker.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def userlog
    @user = User.find_by(id: current_user.id)
    @last_log = current_user.trackers.last


  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      bypass_sign_in @user
      flash[:success] = "Your account was updated successfully"
      redirect_to user_path
    else
      render 'edit'
    end
  end
  def user_params
    params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if user_signed_in?
      # redirect_to user_path(current_user)
      @last_log = current_user.trackers.last
    end


  end

  def attendance

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/attendance/index.html.erb
<div class = "center-table col-lg-12">
  <div class = "table-container col-lg-5 ">
    <p class = "user-head">All Users</p>
  <table cellpadding="20" border-collapse>
    <tr class = "user-info">
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email Address</th>
    </tr>


    <% @users.each do |user| %>
      <tr class = "user-info">
      <td><%= user.firstname %></td>
      <td><%= user.lastname %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>

  </table>
  </div>
  </div>

app/views/attendance/overview.html.erb
<div class = "container ">
  <div class = "panel">
    <div class = "panel-heading"><h4 class="panel-title">Overview</h4></div>
    <div class = "panel-body">
      <table class = "table table-responsive table-bordered">
        <tr>
          <th>Uesr ID</th>
          <th>First Name</t>
          <th>Last Name</th>
          <th>Email</th>
        </tr>
        <% @users.each do |user| %>
        <tr>
            <td><%= user.id %></td>
            <td><%= user.firstname %></td>
            <td><%= user.lastname %></td>
            <td><%= user.email %> </td>
          <% end %>
        </tr>
      </table>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TimeTracker" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>


    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
  <div class="navbar navbar-light bg-primary navbar-static-top">
    <div class = "container-fluid">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'TimeTracker', root_path, class: "navbar-brand" %>
      <div class="navbar-collapse navi collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav">
          <% if user_signed_in? && current_user.admin? %>
<!--            <li class = "nav_link"><%#= link_to current_user.email, edit_registration_path %></li>-->
            <li class = "nav_link"><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
            <li class = "nav_link"><%= link_to 'My Profile', user_path(current_user)%> </li>
            <% elsif user_signed_in? && !current_user.admin? %>
              <li class = "nav_link"><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
              <li class = "nav_link"><%= link_to 'My Profile', user_path(current_user)%></li>
              <li class = "nav_link"><%= link_to "Users", users_path %></li>
            <% else %>
            <li class = "nav_link"><%= link_to "Log in", "/users/sign_in"  %></li>
            <li class = "nav_link"><%= link_to "Sign Up", "/users/sign_up"  %></li>

            <% end %>
        </ul>
      </div>
    </div>
  </div>


    <div class = "the-content">
        <div class="row">
          <div class="container-fluid home-container">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        <!--        <div class="col-lg-3">-->
        <!--          <div class="well sidebar-nav">-->
        <!--            <h3>Sidebar</h3>-->
        <!--            <h3>Sidebar</h3>-->
        <!--            <ul class="nav nav-list">-->
        <!--              <li class="nav-header">Sidebar</li>-->
        <!--              <li><%#= link_to "Link1", "/path1"  %></li>-->
        <!--              <li><%#= link_to "Link2", "/path2"  %></li>-->
        <!--              <li><%#= link_to "Link3", "/path3"  %></li>-->
        <!--            </ul>-->
        <!--          </div><!--/.well -->
        <!--        </div><!--/span-->
      </div><!--/row-->

      <div class = "the-footer">
        <footer>
          <p>Copyright &copy; TimeTracker 2018 by Jhon Baclay</p>
        </footer>
      </div>


    </div> <!-- /container -->

  </body>
</html>

app/views/tracker/index.html.erb
<div>
  <% @trackers.each do |track| %>
    <%= track.user_id %>
    <%= track.loggin_in %></br>
    <%= track.user_id %>

  <% end %>

</div>

app/views/trackers/index.html.erb
<div>
  <% @trackers.each do |track| %>
    <%= track.user_id %>
    <%= track.loggin_in %>
    <%= track.loggin_out %><br>
  <% end %>
  <% @users.each do |user| %>
    <%= user.id %>
    <%= user.firstname %>
    <%= user.lastname %></br>
  <% end %>
  tracker
</div>

app/views/trackers/show.html.erb
<%= current_user.firstname %>

<% @trackers.each do |track| %>
    <%= track.loggin_out %><br/>
<% end %>

app/views/trackers/timein.html.erb
<p><%= @currentTime %></p>

app/views/trackers/timeout.html.erb
<div class="home-container">
  <% if !user_signed_in? %>
    <div class = "tagline">
      <h1>
        Fast and reliable time keeping and attendance system
      </h1>
      <button>Try it now</button>
    </div>

  <% else %>
    <div class = "center_logged">
      <div class = "time-logged">
        <p>Hello <%= current_user.firstname %> !</p>
        <%=t = Time.now
           t.strftime("Printed on %m/%d/%Y")   #=> "Printed on 04/09/2003"
           t.strftime("%I:%M %p")%>
      </div>
      <p>Logged In at:</p>
      <% if @last_log != nil %>
        <%= @last_log.loggin_in.strftime("%I:%M %p") %>
        <% else %>
      <p>Last log is Nil</p>
        <% end %>
      <div class = "the-button">
        <form action="/trackers/timeout" method="POST">
          <button type = 'submit' id = "loggin-button">Time Out</button>

        </form>
      </div>

        </div>
      <% end %>

      </div>

app/views/users/edit.html.erb
<div class="panel panel-default devise-bs container">
  <div class="panel-body">
    <div>
      <h3 class = "text-center"><%= @user.firstname %>'s Information</h3><br/>
    </div>
    <%= form_for(@user, html: { method: :put }) do |f| %>
      <div class="form-group">
        <label>First Name</label>
        <%= f.text_field :firstname, autofocus: true, class: 'form-control' %>
      </div>
      <div class="form-group">
        <label>Last Name</label>
        <%= f.text_field :position, autofocus: true, class: 'form-control' %>
      </div>
      <div class="form-group">
        <label>Position</label>
        <%= f.text_field :position, autofocus: true, class: 'form-control' %>
      </div>
      <div class="form-group">
        <label>Client</label>
        <%= f.text_field :client, autofocus: true, class: 'form-control', readonly: true %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, autofocus: true, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password %> <i>(<%= t('.leave_blank_if_you_don_t_want_to_change_it', default: "Enter password to confirm the changes!") %>)</i>
        <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control'  %>
      </div>
      <div><%= f.submit t('.update', default: 'Update'), class: 'btn btn-primary' %></div><br/>
      <div><%= link_to 'Back to Profile', user_path %></div>
    <% end %>

    <div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class = "container jumbotron">
  <div class="col-lg-2 colm-2">
    <div class="navs"><%= link_to 'Home', root_path %></div>
    <div class="navs"><%= link_to 'Profile', user_path(current_user) %></div>
    <div class="navs">Leaves</div>
    <div class="navs">Calendar</div>
  </div>
  <div class = "panel col-lg-10 col-body">
    <div class = "panel-heading col-body-heading"><h4 class="panel-title">Overview</h4></div>
    <table class = " panel-body table table-responsive table-bordered">
      <tr>
        <th>User ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Position</th>
        <th>Client</th>
        <th>Role</th>
        <th></th>
      </tr>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.firstname %></td>
            <td><%= user.lastname %></td>
            <td><%= user.position %></td>
            <td><%= user.client %></td>
            <% if user.admin %>
              <td>Admin</td>
            <% else %>
              <td>Not Admin </td>
            <% end %>
            <td><%= link_to "View", user_path(user) %>| <%= link_to "Edit", edit_user_path(user) %>| <%= link_to "Delete", user_path(user) %></td>

        <% end %>
      </table>
    </div>
  </div>
</div>

<!--<div class = "container ">-->
<!--  <div class = "panel">-->
<!--    <div class = "panel-heading"><h4 class="panel-title">Overview</h4></div>-->
<!--    <div class = "panel-body">-->
<!--      <table class = "table table-responsive table-bordered">-->
<!--        <tr>-->
<!--          <th>User ID</th>-->
<!--          <th>First Name</th>-->
<!--          <th>Last Name</th>-->
<!--        </tr>-->
        <%# @users.each do |user| %>
<!--                  <tr>-->
<!--                    <td><%#= user.id %></td>-->
<!--                    <td><%#= user.firstname %></td>-->
<!--                    <td><%#= user.lastname %></td>-->
        <%# end %>
<!--      </table>-->
<!--    </div>-->
<!--  </div>-->
<!--</div>-->

app/views/users/show.html.erb
<div class = "container jumbotron">
  <div class="col-lg-2 colm-2">
    <% if @user.trackers.count > 0 %>
      <div class="navs"><%= link_to 'Badge', root_path %></div>
    <% else %>
      <%# if (@last_log.loggin_out != nil) %>
        <div class="navs"><%= link_to 'Start', root_path %></div>
        <%# end %>
    <% end %>
    <div class="navs"><%= link_to "Logs", trackers_userlog_path %></div>
    <div class="navs">Leaves</div>
    <div class="navs">Calendar</div>
  </div>
  <div class = "panel col-lg-10 col-body">
    <div class = "panel-heading col-body-heading "><h4 class="panel-title "><%= @user.firstname %>'s Profile</h4></div>
      <table class = "table table-responsive table-bordered">
        <tr>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Email</th>
          <th>Position</th>
          <th>Client</th>
        </tr>
          <tr>
            <td><%= @user.firstname %></td>
            <td><%= @user.lastname %></td>
            <td><%= @user.email %></td>
            <td><%= @user.position %></td>
            <td><%= @user.client %></td>
        </tr>
      </table>
      <div>
        <p class = "page-navi"><%= link_to 'Edit Profile', edit_user_path %></p>
      </div>


  </div>
</div>

app/views/users/userlog.html.erb
<div class = "container jumbotron">
  <div class="col-lg-2 colm-2">
    <% if current_user.trackers.count > 0 %>
        <div class="navs"><%= link_to 'Punch', root_path %></div>
      <% else %>
        <div class="navs"><%= link_to 'Start', root_path %></div>
      <% end %>
    <div class="navs"><%= link_to 'Profile', user_path(current_user) %></div>
    <div class="navs">Leaves</div>
    <div class="navs">Calendar</div>
  </div>
  <div class = "panel col-lg-10 col-body">
    <div class = "panel-heading col-body-heading"><h4 class="panel-title"><%= @user.firstname %>'s Time Logs</h4></div>
      <table class = " panel-body table table-responsive table-bordered">
        <tr>
          <th>Date</th>
          <th>Log in</th>
          <th>Log out</th>
          <th>Tardy</th>
          <th>Hours Worked</th>
        </tr>

          <% @user.trackers.order(created_at: :desc).each  do |track| %>
          <%# d = DateTime.parse(track.loggin_in.to_s) %>
<!--          <td>day <%#= d.day %></td>-->

            <td> <%= track.created_at.strftime("%b %d, %Y") %></td>

            <% if track.loggin_in != nil %>
              <td><%= track.loggin_in.strftime("%l:%M %p") %></td>
            <% else %>
              <td>No log</td>
            <% end %>
              <% if track.loggin_out != nil %>
            <td><%= track.loggin_out.strftime("%l:%M %p") %></td>
              <% else %>
            <td>No log</td>
           <% end %>
          <td>No data yet</td>
          <% if !track.hours.nil? %>
            <td><%= ((track.hours)/3600.0).round(3) %></td>
          <% else %>
            <td>To be computed</td>
          <% end %>
<!--          <td><%#= ((track.loggin_out - track.loggin_in)/3600.0).round(2) %></td>-->
<!--          <td><%#= track.loggin_in - track.loggin_out %></td>-->
<!--          <td><%#= link_to "Edit log", track %></td>-->
          </tr>
          <% end %>


      </table>
<!--      <div class = "page-navi">-->
<!--        <p><%#= link_to 'Back to profile', user_path(current_user) %></p>-->
<!--      </div>-->
  </div>
</div>

app/views/welcome/index.html.erb
<div class="home-container">
  <% if !user_signed_in? %>
<!--  <div class = "center">-->
<!--    <div class = "time">-->
<!--      <%#=t = Time.now-->
<!--         t.strftime("Printed on %m/%d/%Y")   #=> "Printed on 04/09/2003"-->
         t.strftime("%I:%M %p")%>
<!--    </div>-->
<!--  </div>-->
  <div class = "tagline">
    <h1>
      Fast and reliable time keeping and attendance system
    </h1>
    <button>Try it now</button>
  </div>

    <% else %>
    <div class = "center_logged">
      <div class = "time-logged">
<!--        <p>Hello <%#= current_user.firstname %> !</p>-->
        <%=t = Time.now
           t.strftime("Printed on %m/%d/%Y")   #=> "Printed on 04/09/2003"
           t.strftime("%I:%M %p")%>
      </div>
      <% if current_user.trackers.count > 0 %>
        <% if @last_log.loggin_out == "No log" || @last_log.loggin_out.nil? %>
          <p id = "log-time">Logged In at: <%= @last_log.loggin_in.strftime("%I:%M %p") %></p>

        <div class = "the-button">
          <form action="/trackers/timeout" method="POST">
            <button type = 'submit' id = "loggin-button">Time Out</button>

          </form>
        </div>
          <% elsif @last_log.loggin_in.nil? == false %>
          <p id = "log-time">Logged out at: <%= @last_log.loggin_in.strftime("%I:%M %p") %></p>

          <div class = "the-button">
            <form action="/trackers/timein" method="POST">
              <button type = 'submit' id = "loggin-button">Time In</button>

            </form>
          </div>
          <% else %>
          <p id = "log-time">None of the above</p>
            <p><%= @last_log.loggin_in.strftime("%I:%M %p") %></p>
            <div class = "the-button">
              <form action="/trackers/timein" method="POST">
                <button type = 'submit' id = "loggin-button">Time In</button>

              </form>
            </div>
          <% end %>
        <% else %>
        <div class = "the-button">
          <form action="/trackers/timein" method="POST">
            <button type = 'submit' id = "loggin-button">Time In</button>

          </form>
        </div>
        <% end %>
<!--      <div class = "the-button">-->
<!--        <button id = "login-button"><%#= link_to 'Time in', trackers_timein_path %></button>-->
<!--      </div>-->

</div>
    <% end %>

</div>


<!--Original page-->

<!--<div class="home-container">-->
  <%# if !user_signed_in? %>
<!--  <div class = "tagline">-->
<!--    <h1>-->
<!--      Fast and reliable time keeping and attendance system-->
<!--    </h1>-->
<!--    <button><%#= link_to "Try it now!", new_user_registration_path %></button>-->
<!--  </div>-->

    <%# else %>
<!--    <div class = "center_logged">-->
<!--      <div class = "time-logged">-->
<!--        <p>Hello <%#= current_user.firstname %> !</p>-->
<!--        <%#=t = Time.now-->
<!--           t.strftime("Printed on %m/%d/%Y")   #=> "Printed on 04/09/2003"-->
           t.strftime("%I:%M %p")%>
<!--      </div>-->
<!--      <div class = "the-button">-->
<!--      <button><%#= link_to 'Time in', trackers_timein_path %></button>-->
<!--      </div>-->

<!--</div>-->
    <%# end %>

<!--</div>-->